block 0
446264394:this := @this: org.apache.hadoop.hbase.avro.generated.AIOError
839404033:field$ := @parameter0: int
389245499:if field$ == 0 goto $stack2 = this.<org.apache.hadoop.hbase.avro.generated.AIOError: org.apache.avro.util.Utf8 message>
block 1
2036110451:goto [?= $stack3 = new org.apache.avro.AvroRuntimeException]
block 3
917379055:$stack3 = new org.apache.avro.AvroRuntimeException
1221676704:specialinvoke $stack3.<org.apache.avro.AvroRuntimeException: void <init>(java.lang.String)>("Bad index")
556080707:throw $stack3
block 2
1398492607:$stack2 = this.<org.apache.hadoop.hbase.avro.generated.AIOError: org.apache.avro.util.Utf8 message>
1331108878:return $stack2
