block 0
1558454047:this := @this: org.apache.hadoop.hbase.avro.generated.AAlreadyExists
1451361350:field$ := @parameter0: int
576312655:value$ := @parameter1: java.lang.Object
437313470:if field$ == 0 goto $stack3 = (org.apache.avro.util.Utf8) value$
block 1
1142722504:goto [?= $stack4 = new org.apache.avro.AvroRuntimeException]
block 3
681375707:$stack4 = new org.apache.avro.AvroRuntimeException
927008541:specialinvoke $stack4.<org.apache.avro.AvroRuntimeException: void <init>(java.lang.String)>("Bad index")
891122284:throw $stack4
block 2
1129983101:$stack3 = (org.apache.avro.util.Utf8) value$
1468031814:this.<org.apache.hadoop.hbase.avro.generated.AAlreadyExists: org.apache.avro.util.Utf8 message> = $stack3
1078027041:goto [?= return]
block 4
395393387:return
block 0
1558454047:this := @this: org.apache.hadoop.hbase.avro.generated.AAlreadyExists
1451361350:field$ := @parameter0: int
576312655:value$ := @parameter1: java.lang.Object
1262170348:if field$ == 0 goto $stack3 = (org.apache.avro.util.Utf8) value$
block 1
382391138:goto [?= $stack4 = new org.apache.avro.AvroRuntimeException]
block 3
681375707:$stack4 = new org.apache.avro.AvroRuntimeException
927008541:specialinvoke $stack4.<org.apache.avro.AvroRuntimeException: void <init>(java.lang.String)>("Bad index")
891122284:throw $stack4
block 2
1129983101:$stack3 = (org.apache.avro.util.Utf8) value$
1468031814:this.<org.apache.hadoop.hbase.avro.generated.AAlreadyExists: org.apache.avro.util.Utf8 message> = $stack3
1078027041:goto [?= return]
block 4
395393387:return
